# Generated by Django 2.1.5 on 2019-11-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hueauth',
            name='user_name_device',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
